//#ifndef SFML_GRAPHICS
//#	define SFML_GRAPHICS
#	include <SFML/Graphics.hpp>
//#endif // !SFML_GRAPHICS

const int HEIGHT_MAP = 25;
const int WIDTH_MAP = 25;

sf::String TileMap[HEIGHT_MAP] = {
	"MMMMMMMMMMMMMMMMMMMMMMMMM",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"M M M M M M M M M M M M M",
	"M                       M",
	"MMMMMMMMMMMMMMMMMMMMMMMMM",
};

/*sf::String TileMap[HEIGHT_MAP] = {
	"MMMMMMMMMMMMMMMMMMMMMMMMM",
	"M  SSSSSSSSSSSSSSSSSSS  M",
	"M MSMSMSMSMSMSMSMSMSMSM M",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"MSMSMSMSMSMSMSMSMSMSMSMSM",
	"MSSSSSSSSSSSSSSSSSSSSSSSM",
	"M MSMSMSMSMSMSMSMSMSMSM M",
	"M  SSSSSSSSSSSSSSSSSSS  M",
	"MMMMMMMMMMMMMMMMMMMMMMMMM",
};*/